/**
 * Turns the curated originals into web assets.
 *
 * Each pick becomes ONE optimized JPEG in `public/photos/`, sized to fit within
 * MAX_EDGE. `next/image` re-encodes those to AVIF/WebP per request and picks a
 * width from `deviceSizes`, so shipping a single high-quality source is both
 * smaller in git and more flexible than pre-cutting every breakpoint.
 *
 * Also emits `src/lib/photos.ts`: intrinsic dimensions (next/image needs them
 * for local files) plus a base64 LQIP so every picture has a blur placeholder.
 *
 * Requires ImageMagick 7. Run: bun run assets:photos
 */
import { $ } from "bun";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { PHOTOS, type PhotoPick } from "./photos.manifest";

const OUT_DIR = "public/photos";
const MANIFEST = "src/lib/photos.ts";
const MAX_EDGE = 2400;
const QUALITY = 82;
/** Width of the inline blur placeholder. Small enough to stay a short string. */
const LQIP_WIDTH = 16;

type Processed = PhotoPick & { width: number; height: number; blur: string };

async function encode(pick: PhotoPick): Promise<Processed> {
  const out = join(OUT_DIR, `${pick.id}.jpg`);

  // `-auto-orient` bakes in the EXIF rotation, `-strip` drops the rest of the
  // metadata (including GPS from the camera), and the trailing `>` in the
  // geometry only ever downscales. The geometry has to be one interpolated
  // value or Bun's shell reads that `>` as a redirection.
  const geometry = `${MAX_EDGE}x${MAX_EDGE}>`;
  await $`magick ${pick.src} -auto-orient -strip -resize ${geometry} -quality ${QUALITY} -interlace Plane ${out}`.quiet();

  const size = await $`magick identify -format "%w %h" ${out}`.quiet().text();
  const [width, height] = size.trim().split(" ").map(Number);

  const lqipGeometry = `${LQIP_WIDTH}x`;
  const lqip = await $`magick ${out} -resize ${lqipGeometry} -quality 40 jpg:-`
    .quiet()
    .arrayBuffer();
  const blur = `data:image/jpeg;base64,${Buffer.from(lqip).toString("base64")}`;

  return { ...pick, width, height, blur };
}

function renderManifest(photos: Processed[]): string {
  const entries = photos
    .map(
      (p) =>
        `  "${p.id}": {\n` +
        `    src: "/photos/${p.id}.jpg",\n` +
        `    width: ${p.width},\n` +
        `    height: ${p.height},\n` +
        `    slot: "${p.slot}",\n` +
        `    alt: ${JSON.stringify(p.alt)},\n` +
        `    blur: "${p.blur}",\n` +
        `  },`,
    )
    .join("\n");

  return `// GENERATED by scripts/process-photos.ts — do not edit by hand.
// Edit scripts/photos.manifest.ts and re-run \`bun run assets:photos\`.

export type PhotoSlot = "hero" | "interior" | "craft" | "detail" | "exterior";

export type Photo = {
  src: string;
  width: number;
  height: number;
  slot: PhotoSlot;
  alt: string;
  /** Base64 LQIP for next/image's \`placeholder="blur"\`. */
  blur: string;
};

export const photos = {
${entries}
} as const satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;

/** Every picture assigned to a section, in manifest order. */
export function photosInSlot(slot: PhotoSlot): (Photo & { id: PhotoId })[] {
  return (Object.entries(photos) as [PhotoId, Photo][])
    .filter(([, p]) => p.slot === slot)
    .map(([id, p]) => ({ ...p, id }));
}
`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const processed: Processed[] = [];
  for (const pick of PHOTOS) {
    const p = await encode(pick);
    processed.push(p);
    console.info(`  ${p.id}.jpg  ${p.width}×${p.height}`);
  }

  await writeFile(MANIFEST, renderManifest(processed));
  console.info(`\n${processed.length} photos → ${OUT_DIR}, manifest → ${MANIFEST}`);
}

await main();
